version: '3'
services:
        db:
                image: postgres
                restart: always
                environment:
                        POSTGRES_PASSWORD: 1234567890
                ports:
                  - 5432:5432

        adminer:
                image: adminer
                restart: always
                ports:
                        - 1000:8080
        mylaps:
                image: mylaps
                restart: always
                environment:
                        AMB1IP: 192.168.1.200
