version: '3'
services:
        db:
                image: postgres
                restart: always
                environment:
                        POSTGRES_PASSWORD: 1234567890
        
        adminer:
                image: adminer
                restart: always
                ports:
                        - 1000:8080
